import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#ffffff',
  '--slot4-page-text': '#1e2229',
  '--slot4-panel-bg': '#fbfbfc',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#505972',
  '--slot4-soft-muted-text': '#838da9',
  '--slot4-accent': '#3a7dff',
  '--slot4-accent-fill': '#3a7dff',
  '--slot4-accent-soft': '#eaf4ff',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#1e2229',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#edeff3',
  '--slot4-cream': '#ffffff',
  '--slot4-warm': '#fbfbfc',
  '--slot4-lavender': '#f2f1ff',
  '--slot4-gray': '#edeff3',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#ffffff',
  '--editable-page-text': '#1e2229',
  '--editable-container': '1268px',
  '--editable-border': '#edeff3',
  '--editable-nav-bg': '#ffffff',
  '--editable-nav-text': '#1e2229',
  '--editable-nav-active': '#3a7dff',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#1e2229',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#ffffff',
  '--editable-footer-text': '#1e2229',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_2px_7px_rgba(20,20,43,0.06)]',
  shadowStrong: 'shadow-[0_8px_28px_rgba(20,20,43,0.10)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(30,34,41,0.04),rgba(30,34,41,0.78))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-6',
    sectionY: 'py-[100px] lg:py-[180px]',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[140px] shrink-0 snap-start sm:w-[160px]',
  },
  type: {
    eyebrow: 'text-xs font-semibold uppercase tracking-[0.16em] text-[var(--slot4-accent)]',
    heroTitle: 'text-[42px] font-bold leading-[1.12] sm:text-[52px]',
    sectionTitle: 'text-[32px] font-bold leading-[1.313] sm:text-[38px]',
    body: 'text-base leading-[1.75]',
    emphasis: 'text-[22px] font-semibold leading-[1.636]',
  },
  surface: {
    card: `rounded-[20px] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[20px] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[20px] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-dark-bg)] px-7 py-4 text-sm font-bold text-white transition duration-300 hover:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-white px-7 py-4 text-sm font-semibold text-[var(--slot4-page-text)] shadow-[0_4px_10px_rgba(20,20,43,0.04)] transition duration-300 hover:scale-[0.98] hover:border-[var(--slot4-accent)] hover:bg-[var(--slot4-accent)] hover:text-white`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.accentBg} px-7 py-4 text-sm font-bold text-[var(--slot4-on-accent)] transition duration-300 hover:scale-[0.98]`,
    ghost: `inline-flex items-center justify-center gap-2 rounded-full px-4 py-3 text-sm font-semibold text-[var(--slot4-muted-text)] transition duration-300 hover:text-[var(--slot4-page-text)]`,
  },
  badge: {
    pill: 'inline-flex items-center gap-2 rounded-full border border-[var(--editable-border)] bg-white px-4 py-2 text-xs font-semibold text-[var(--slot4-muted-text)]',
    accentPill: 'inline-flex items-center gap-2 rounded-full bg-[var(--slot4-accent-soft)] px-4 py-2 text-xs font-semibold text-[var(--slot4-accent)]',
  },
  media: {
    frame: `relative overflow-hidden rounded-[20px] ${editablePalette.mediaBg}`,
    frameFull: `relative overflow-hidden rounded-[24px] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[16/10]',
  },
  motion: {
    lift: 'transition duration-300 hover:scale-[0.98]',
    fade: 'transition duration-300 hover:opacity-80',
    zoom: 'transition duration-500 group-hover:scale-[1.03]',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing, like the MysteryCoder reference layout.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
